# Generated by Django 4.0.6 on 2024-08-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_merge_0003_auto_20210726_1109_0003_auto_20210727_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
